DROP TABLE users;
DROP TABLE IF EXISTS shorten_url;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shorten_url(
  id SERIAL PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  short_url VARCHAR(255)  NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
